"""Step 03: build prompts for one split (default pilot). T0 texts come from data/prompts/t0_texts.jsonl
if present (generated by the judge model with scripts/03b_generate_t0.py); otherwise T0 is skipped.
Also exports data/annotation/t3_review.csv so the automatic first-person conversions can be checked."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

from vcd.config import load_e0
from vcd.data.framings import make_prompts, variant_body_and_stem
from vcd.io import load_models, read_jsonl, write_jsonl
from vcd.schemas import Family


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/e0.yaml")
    ap.add_argument("--split", default="pilot")
    ap.add_argument("--out", default=None, help="override output path")
    args = ap.parse_args()
    cfg = load_e0(args.config)

    fams = [f for f in load_models(cfg["paths"]["families"], Family) if f.split == args.split]
    t0_path: Path = cfg["paths"]["t0_texts"]
    t0 = {r["family_id"]: r["text"] for r in read_jsonl(t0_path)} if t0_path.exists() else {}
    variants = list(cfg["variants_all"])
    if not t0:
        variants = [v for v in variants if v != "T0"]
        print("T0 texts not found; building without T0 (run 03b_generate_t0.py with the judge model first)")

    prompts, flag_counts, review_rows = [], Counter(), []
    for f in fams:
        vs = variants if f.family_id in t0 or "T0" not in variants else [v for v in variants if v != "T0"]
        ps, flags = make_prompts(f, vs, t0.get(f.family_id))
        prompts += ps
        flag_counts.update(flags)
        if f.item_form == "two_action":
            body, _, _ = variant_body_and_stem(f, "T3", None)
            review_rows.append({"family_id": f.family_id, "situation_2nd": f.situation, "situation_1st_auto": body, "ok(1/0)": "", "corrected_text": ""})

    out = Path(args.out) if args.out else cfg["paths"]["prompts"]
    n = write_jsonl(out, prompts)
    print(f"{len(fams)} families in split '{args.split}' -> {n} prompts -> {out}")
    print("variants:", dict(Counter(p.variant for p in prompts)))
    print("flags:", dict(flag_counts))

    ann_dir: Path = cfg["paths"]["annotation_dir"]
    ann_dir.mkdir(parents=True, exist_ok=True)
    with open(ann_dir / f"t3_review_{args.split}.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(review_rows[0].keys()) if review_rows else ["family_id"])
        w.writeheader()
        w.writerows(review_rows)
    print(f"T3 review sheet -> {ann_dir / f't3_review_{args.split}.csv'}")


if __name__ == "__main__":
    main()
